name: cloudcom_final
description: Simple monster detector demo
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  http: ^1.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  torch_light: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true